### ISSUE TITLE
Readme not up to date with passing additional options such as HA

### ISSUE THREAD

**Issue by Vince-Cercury** [docker-flink/examples#5]
The readme references the old way of passing the options to the Flink template. A recent commit has broken that.
Example of what to use:

` 
flink:
  jobmanager_heap_mb: 1024
  taskmanager_heap_mb: 8192
  num_taskmanagers: 2
  num_slots_per_taskmanager: 4
  config: |
    taskmanager.memory.preallocate: false
    parallelism.default: 4
    high-availability: zookeeper
    high-availability.zookeeper.quorum: ....
    high-availability.zookeeper.path.root: /flink
    high-availability.zookeeper.path.cluster-id: /default_ns
    high-availability.storageDir: s3://...
    high-availability.zookeeper.storageDir: s3://....
    high-availability.jobmanager.port: 6123
    high-availability.zookeeper.client.acl: open`

Passing the additional options this way works for me.

Im happy to propose a PR if this project is active?

**Comment by iemejia** [comment]
Hi, sure this project is for sure active and is being updated with every new release of Flink. Please provide a PR. Notice that if the old way works still with earlier versions of Flink we should probably clarify that 'since version 1.x we should do ...' I am curious anyway Flink is quite strict about backward compatiblity.

**Comment by Vince-Cercury** [comment]
PR: https://github.com/docker-flink/examples/pull/7

**Comment by patricklucas** [comment]
Fixed #7

@iemejia afaik this is just about fixing how the example chart handle params, not anything to do with Flink proper. Since this is definitely still "alpha" and unpublished in any official way, I'm totally fine with breaking changes to the chart and examples.
