### ISSUE TITLE
Job manager Liveliness prob

### ISSUE THREAD

**Issue by Vince-Cercury** [docker-flink/examples#6]
`        livenessProbe:
          httpGet:
            path: /overview
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10`

A livelinessProbe is important, especially in HA. We want to make sure the Job Manager was elected as a leader. Sometimes I observed it getting stuck if the Job manager start before the Zookeeper cluster is up and running. It hangs waiting for Zookeeper to elect a leader and never completes.
This livenessProbe has fixed that issue. 

If the job manager cannot see a leader, it will return an error, which will get captured by the livenessProbe. Kubernetes will eventually restart the container

**Comment by Vince-Cercury** [comment]
PR: https://github.com/docker-flink/examples/pull/8

**Comment by patricklucas** [comment]
Fixed #8
